# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_dep', models.CharField(default='', max_length=100)),
                ('text_arr', models.CharField(default='', max_length=100)),
                ('city_dep', models.CharField(max_length=10)),
                ('city_arr', models.CharField(max_length=10)),
                ('rinko_dep', models.CharField(max_length=10)),
                ('rinko_arr', models.CharField(max_length=10)),
            ],
        ),
    ]
